export const LAY_DANH_SACH_PHIM = 'LAY_DANH_SACH_PHIM';
export const LAY_CHI_TIET_PHIM = ' LAY_CHI_TIET_PHIM';
export const LAY_THONG_TIN_HE_THONG_RAP = 'LAY_THONG_TIN_HE_THONG_RAP';
export const LAY_THONG_TIN_LICH_CHIEU = 'LAY_THONG_TIN_LICH_CHIEU';
export const DAT_GHE = 'DAT_GHE';
export const DAT_VE = 'DAT_VE';
export const LAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP='LAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP';
